DROP TABLE brands IF EXISTS CASCADE;

CREATE TABLE BRANDS (
   ID BIGINT(20) NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(20) NOT NULL,
   PRIMARY KEY (id));

INSERT INTO BRANDS (ID, NAME)
VALUES (1, 'ZARA');